### ISSUE TITLE
Code for "Enhancing Adversarial Robustness for Deep Metric Learning"

### ISSUE THREAD

**Issue by cosmolu** [cdluminate/robrank#14]
Hi Mo,

I am reading your new paper "Enhancing Adversarial Robustness for Deep Metric Learning". It is quite interesting and the performance is good! May I ask is there any code for it? Or do you prepare to update the code for the new method HM? :) 
Thanks.

Best regards,
Cosmo

**Comment by cdluminate** [comment]
If you have read the two readme files
(1) https://github.com/cdluminate/robdml
(2) https://github.com/cdluminate/robrank 

You will be able to track down into the code, and find that
(1) `hm_training_step` in https://github.com/cdluminate/robrank/blob/main/robrank/defenses/amd.py is the HM defense in CVPR2022 paper.
(2) `pnp_training_step` in https://github.com/cdluminate/robrank/blob/main/robrank/defenses/pnp.py is the ACT defense.

I will update the readme to point out the specific function positions. Does the above pointer resolve your concern?

**Comment by cdluminate** [comment]
Hi, I have updated the README to clearly point out the code position, see https://github.com/cdluminate/robrank/commit/711179a3f241acd076b0be1d6162f823da485124 
Please comment if you have further questions. 

Thank you!

**Comment by cosmolu** [comment]
Hi Mo, thank you for such a quick reply! It is clear and it solves my problems, thank you!
