### ISSUE TITLE
Training deep metric learning model

### ISSUE THREAD

**Issue by bingxumu** [cdluminate/robrank#5]
Hi, Thanks for your great work!

When I run the command 'python3 bin/train.py -C mnist:rc2f2:ptripletN --do_test', I got the output log as follows:
![image](https://user-images.githubusercontent.com/51730679/123517535-15acf780-d6d4-11eb-87d2-afc9d9718aad.png)
I don't make any change of the original code. Could you give me some advice about it?

My mainly environment:
Python: 3.8.5 (anaconda)
PyTorch: 1.8.1+cu111
GPU: Nvidia RTX3090 (24GB)

Thanks

**Comment by cdluminate** [comment]
This problem is irrelevant to this repository. Check your python library installation (e.g. faiss). Or you can temporarily disable faiss on GPU by exporting `FAISS_CPU=1`.

**Comment by bingxumu** [comment]
Thanks!
I reduced the version of faiss-gpu to 1.7.0 and the problem was resolved.
